# 站点信息
title: 我的笔记
tagline: SiYuan Notes
lang: zh-CN
timezone: Asia/Shanghai

url: "https://zhongloul.github.io"
baseurl: "/siyuan-notes"

theme: jekyll-theme-chirpy

github:
  username: Zhongloul

theme_mode: light

# 首页文章列表分页
paginate: 10

# 侧边栏 Tab 集合（标签/分类/归档必须定义这里才显示）
collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/

toc: true
